from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from datetime import datetime


def _text(parent: ET.Element, name: str, value: object | None) -> None:
    if value is None:
        return
    text = str(value).strip()
    if text == "":
        return
    ET.SubElement(parent, name).text = text


def _parse_date(value: str) -> tuple[int | None, int | None, int | None]:
    raw = (value or "").strip()
    if not raw or raw == "0":
        return None, None, None

    match = re.search(r"(\d{4})[-/.年](\d{1,2})[-/.月](\d{1,2})", raw)
    if match:
        return int(match.group(1)), int(match.group(2)), int(match.group(3))

    for fmt in ("%Y-%m-%d", "%Y/%m/%d", "%Y.%m.%d"):
        try:
            dt = datetime.strptime(raw[:10], fmt)
            return dt.year, dt.month, dt.day
        except ValueError:
            pass

    return None, None, None


def build_comicinfo_xml(
    *,
    album,
    photo,
    title: str,
    number: int,
    count: int,
    page_count: int,
    web: str,
) -> str:
    root = ET.Element("ComicInfo")
    root.set("xmlns:xsd", "http://www.w3.org/2001/XMLSchema")
    root.set("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")

    tags = []
    for group_name in ("tags", "works", "actors"):
        for item in getattr(album, group_name, []) or []:
            if item and item not in tags:
                tags.append(str(item))

    authors = [str(author) for author in getattr(album, "authors", []) or [] if author]
    if not authors and getattr(album, "author", ""):
        authors = [str(album.author)]

    _text(root, "Series", getattr(album, "title", getattr(album, "name", "")))
    _text(root, "Title", title)
    _text(root, "Number", number)
    _text(root, "Count", count)
    _text(root, "Summary", getattr(album, "description", ""))
    _text(root, "Writer", ", ".join(authors))
    _text(root, "Tags", ", ".join(tags))
    _text(root, "Web", web)
    _text(root, "PageCount", page_count)
    _text(root, "Manga", "YesAndRightToLeft")
    _text(root, "Notes", f"Generated by JM Downloader. JM album id: {album.id}; JM photo id: {photo.id}")

    year, month, day = _parse_date(getattr(album, "pub_date", ""))
    _text(root, "Year", year)
    _text(root, "Month", month)
    _text(root, "Day", day)

    ET.indent(root, space="  ")
    return ET.tostring(root, encoding="unicode", xml_declaration=True)
